#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd


# run Verilator to translate Verilog into C++, including C++ testbench
# -- PC -- #
verilator -cc mux.sv                    
verilator -cc register.sv
verilator -cc PC.sv     
# -- instruction memory / sign extend -- #
verilator -cc instrmem.sv
verilator -cc signextend.sv
# -- CU -- #
verilator -cc main_decoder.sv
verilator -cc alu_decoder.sv
verilator -cc CU.sv
# -- RMA -- #
verilator -cc RegFile.sv
verilator -cc ALU_Mux.sv
verilator -cc ALU.sv
verilator -cc RMA.sv
# -- Top File -- #
verilator -Wall --cc --trace Top.sv --exe Top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VTop.mk VTop

# run executable simulation
obj_dir/VTop