#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f CU.vcd


# run Verilator to translate Verilog into C++, including C++ testbench
# -- CU -- #
verilator -cc main_decoder.sv
verilator -cc alu_decoder.sv
verilator -Wall --cc --trace CU.sv --exe CU_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VCU.mk VCU

# run executable simulation
obj_dir/VCU