#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f PC.vcd


# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace PC.sv mux.sv register.sv --exe PC_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VPC.mk VPC

# run executable simulation
obj_dir/VPC